// ===== ТОВАРЫ =====
// window.PRODUCTS чтобы было видно из ES-модулей
window.PRODUCTS = [
  // ФИГУРКИ
  {
    id: 1,
    name: 'Фигурка Леви Аккерман',
    title: 'Атака Титанов',
    category: 'figures',
    price: 1890,
    emoji: '⚔️',
    badge: 'new',
  },
  {
    id: 2,
    name: 'Фигурка Наруто Узумаки',
    title: 'Naruto Shippuden',
    category: 'figures',
    price: 2200,
    oldPrice: 2600,
    emoji: '🍥',
    badge: 'sale',
  },
  {
    id: 3,
    name: 'Фигурка Зеро Ту',
    title: 'Darling in the FranXX',
    category: 'figures',
    price: 2750,
    emoji: '🌸',
    badge: null,
  },
  {
    id: 4,
    name: 'Фигурка Тандзиро Камадо',
    title: 'Клинок рассекающий демонов',
    category: 'figures',
    price: 1990,
    emoji: '🔥',
    badge: 'new',
  },
  {
    id: 5,
    name: 'Фигурка Луффи Gear 5',
    title: 'One Piece',
    category: 'figures',
    price: 3100,
    emoji: '🏴‍☠️',
    badge: null,
  },

  // ПОСТЕРЫ
  {
    id: 6,
    name: 'Постер «Атака Титанов»',
    title: 'Attack on Titan',
    category: 'posters',
    price: 490,
    emoji: '🖼️',
    badge: null,
  },
  {
    id: 7,
    name: 'Постер «Туалетный мальчик»',
    title: 'Toilet-bound Hanako-kun',
    category: 'posters',
    price: 450,
    emoji: '🚽',
    badge: 'new',
  },
  {
    id: 8,
    name: 'Постер «Магическая битва»',
    title: 'Jujutsu Kaisen',
    category: 'posters',
    price: 490,
    emoji: '💜',
    badge: null,
  },
  {
    id: 9,
    name: 'Картина «Унесённые призраками»',
    title: 'Studio Ghibli',
    category: 'posters',
    price: 890,
    oldPrice: 1100,
    emoji: '🌊',
    badge: 'sale',
  },

  // КУЛОНЫ
  {
    id: 10,
    name: 'Кулон «Глаз Шаринган»',
    title: 'Naruto',
    category: 'pendants',
    price: 390,
    emoji: '👁️',
    badge: null,
  },
  {
    id: 11,
    name: 'Кулон «Символ Клинка»',
    title: 'Клинок рассекающий демонов',
    category: 'pendants',
    price: 350,
    emoji: '⚡',
    badge: 'new',
  },
  {
    id: 12,
    name: 'Кулон «Сердце Луффи»',
    title: 'One Piece',
    category: 'pendants',
    price: 320,
    emoji: '❤️',
    badge: null,
  },
  {
    id: 13,
    name: 'Кулон «Тотем Тоторо»',
    title: 'Studio Ghibli',
    category: 'pendants',
    price: 410,
    emoji: '🌿',
    badge: null,
  },

  // АКСЕССУАРЫ
  {
    id: 14,
    name: 'Брелок «Пикачу»',
    title: 'Pokemon',
    category: 'accessories',
    price: 290,
    emoji: '⚡',
    badge: null,
  },
  {
    id: 15,
    name: 'Значок «Акацки»',
    title: 'Naruto',
    category: 'accessories',
    price: 150,
    emoji: '☁️',
    badge: null,
  },
  {
    id: 16,
    name: 'Набор значков «JJK»',
    title: 'Jujutsu Kaisen',
    category: 'accessories',
    price: 390,
    oldPrice: 490,
    emoji: '🎴',
    badge: 'sale',
  },
  {
    id: 17,
    name: 'Сумка-шоппер «Аниме»',
    title: 'Animuchi Original',
    category: 'accessories',
    price: 790,
    emoji: '🛍️',
    badge: 'new',
  },

  // K-POP
  {
    id: 18,
    name: 'Фотокарточки BTS',
    title: 'BTS',
    category: 'kpop',
    price: 250,
    emoji: '💜',
    badge: null,
  },
  {
    id: 19,
    name: 'Брелок STRAY KIDS',
    title: 'Stray Kids',
    category: 'kpop',
    price: 320,
    emoji: '🐺',
    badge: 'new',
  },
  {
    id: 20,
    name: 'Значки BLACKPINK',
    title: 'BLACKPINK',
    category: 'kpop',
    price: 190,
    emoji: '🌸',
    badge: null,
  },
];
    emoji: '🌸',
    badge: null,
  },
];
